[package]
name = "sdk-python"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sdk-core = { version = "0.1.1", path = "./../../sdk-core" }
pyo3 = { version = "0.20.2", features = ["extension-module", "abi3-py38"] }

[profile.release]
strip = "debuginfo"