[package]
name = "sdk-typescript"
version = "0.1.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
sdk-core = { version = "0.1.1", path = "./../../sdk-core" }
neon = { version = "0.10.1", default-features = false, features = ["napi-6"] }
